<ToolPaletteExport><DependentFilesPath>mp-Draw</DependentFilesPath><PaletteSets><PaletteSetData><PaletteSetContent><Palettes><PaletteData><PaletteContent><Palette Revision="24.2.1" option="0"><ItemID idValue="{4C6CD2DF-662E-4F45-AC8D-FE0E8B869967}"/><Properties><ItemName>mp-Draw</ItemName><Images option="0"/></Properties><Tools><Tool Revision="24.2.1" option="0"><ItemID idValue="{DCA8FC24-AE40-4B85-AC1A-61D852762CE2}"/><Properties><ItemName>Line</ItemName><Images option="0"><Image cx="20" cy="20" IsDark="false" resource="RCDATA_16_LINE" src="%ProgramBtnRes%"/><Image cx="20" cy="20" IsDark="true" resource="RCDATA_16_LINE" src="%ProgramBtnRes%"/></Images><Description>Creates straight line segments</Description><Time createdUniversalDateTime="2022-02-14T04:44:14" modifiedUniversalDateTime="2022-02-14T04:44:14"/></Properties><CustomData>
											<AcRxClassInfo className="AcDbLine"/>
											<ToolbarButton idButton="ID_Line"/>
										</CustomData>
										<ToolType>2</ToolType><Flyout enable="true"><ShapePackage idValue="{4AFD3A7B-127C-468D-9DAD-D6D948BA8615}"/><CurrentShape idValue="{A7FC31D7-54EB-4CC8-B5D8-539D51522D1A}"/></Flyout><StockToolRef idValue="{2AE7120B-CEE4-47A5-9B50-EF9F3ADE24AC}"/><Data>
											<GeneralProperties><Color><BasicPropInfo><PropValue unspecified="TRUE"/></BasicPropInfo></Color><Layer><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Layer><Linetype><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Linetype><LinetypeScale><BasicPropInfo><PropValue unspecified="TRUE" valueType="3" value="0"/></BasicPropInfo></LinetypeScale><PlotStyle><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></PlotStyle><LineWeight><BasicPropInfo><PropValue unspecified="TRUE" valueType="2" value="0"/></BasicPropInfo></LineWeight><Transparency><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Transparency><Textstyle><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Textstyle><Dimstyle><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Dimstyle><Tablestyle><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Tablestyle></GeneralProperties><Command><Macro><![CDATA[^C^C_line ]]></Macro></Command></Data>
									</Tool><Tool Revision="24.2.1" option="0"><ItemID idValue="{A3564D00-90E3-4147-8156-558F6C129BD4}"/><Properties><ItemName>Construction Line</ItemName><Images option="0"><Image cx="20" cy="20" IsDark="false" resource="RCDATA_16_XLINE" src="%ProgramBtnRes%"/><Image cx="20" cy="20" IsDark="true" resource="RCDATA_16_XLINE" src="%ProgramBtnRes%"/></Images><Description>Creates a line of infinite length</Description><Time createdUniversalDateTime="2022-02-14T04:44:14" modifiedUniversalDateTime="2022-02-14T04:44:14"/></Properties><CustomData>
											<AcRxClassInfo className="AcDbXline"/>
											<ToolbarButton idButton="ID_Xline"/>
										</CustomData>
										<ToolType>2</ToolType><Flyout enable="true"><ShapePackage idValue="{4AFD3A7B-127C-468D-9DAD-D6D948BA8615}"/><CurrentShape idValue="{25BB7D34-0E8F-4A36-B852-AEA08205923E}"/></Flyout><StockToolRef idValue="{2AE7120B-CEE4-47A5-9B50-EF9F3ADE24AC}"/><Data>
											<GeneralProperties><Color><BasicPropInfo><PropValue unspecified="TRUE"/></BasicPropInfo></Color><Layer><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Layer><Linetype><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Linetype><LinetypeScale><BasicPropInfo><PropValue unspecified="TRUE" valueType="3" value="0"/></BasicPropInfo></LinetypeScale><PlotStyle><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></PlotStyle><LineWeight><BasicPropInfo><PropValue unspecified="TRUE" valueType="2" value="0"/></BasicPropInfo></LineWeight><Transparency><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Transparency><Textstyle><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Textstyle><Dimstyle><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Dimstyle><Tablestyle><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Tablestyle></GeneralProperties><Command><Macro><![CDATA[^C^C_xline ]]></Macro></Command></Data>
									</Tool><Tool Revision="24.2.1" option="0"><ItemID idValue="{2161258F-3E15-436E-9FBC-E8F25F509F36}"/><Properties><ItemName>Polyline</ItemName><Images option="0"><Image cx="20" cy="20" IsDark="false" resource="RCDATA_16_PLINE" src="%ProgramBtnRes%"/><Image cx="20" cy="20" IsDark="true" resource="RCDATA_16_PLINE" src="%ProgramBtnRes%"/></Images><Description>Creates a 2D polyline</Description><Time createdUniversalDateTime="2022-02-14T04:44:14" modifiedUniversalDateTime="2022-02-14T04:44:14"/></Properties><CustomData>
											<AcRxClassInfo className="AcDb2dPolyline"/>
											<ToolbarButton idButton="ID_Pline"/>
										</CustomData>
										<ToolType>2</ToolType><Flyout enable="true"><ShapePackage idValue="{4AFD3A7B-127C-468D-9DAD-D6D948BA8615}"/><CurrentShape idValue="{63B4EA09-B9B3-45BC-B864-E7A22A7EFAF2}"/></Flyout><StockToolRef idValue="{2AE7120B-CEE4-47A5-9B50-EF9F3ADE24AC}"/><Data>
											<GeneralProperties><Color><BasicPropInfo><PropValue unspecified="TRUE"/></BasicPropInfo></Color><Layer><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Layer><Linetype><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Linetype><LinetypeScale><BasicPropInfo><PropValue unspecified="TRUE" valueType="3" value="0"/></BasicPropInfo></LinetypeScale><PlotStyle><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></PlotStyle><LineWeight><BasicPropInfo><PropValue unspecified="TRUE" valueType="2" value="0"/></BasicPropInfo></LineWeight><Transparency><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Transparency><Textstyle><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Textstyle><Dimstyle><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Dimstyle><Tablestyle><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Tablestyle></GeneralProperties><Command><Macro><![CDATA[^C^C_pline ]]></Macro></Command></Data>
									</Tool><Tool Revision="24.2.1" option="24"><ItemID idValue="{EFDF30CF-4BC5-4BD9-9B4D-ADB08DA0AB4B}"/><Properties><ItemName>Polygon</ItemName><Images option="0"><Image cx="20" cy="20" IsDark="false" resource="RCDATA_16_POLYGO" src="%ProgramBtnRes%"/><Image cx="20" cy="20" IsDark="true" resource="RCDATA_16_POLYGO" src="%ProgramBtnRes%"/></Images><Description>Creates an equilateral closed polyline</Description><Time createdUniversalDateTime="2022-02-14T04:34:52" modifiedUniversalDateTime="2022-02-14T04:34:52"/></Properties><ToolType>1</ToolType><StockToolRef idValue="{2AE7120B-CEE4-47A5-9B50-EF9F3ADE24AC}"/><Data><GeneralProperties><Color><BasicPropInfo><PropValue unspecified="TRUE"/></BasicPropInfo></Color><Layer><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Layer><Linetype><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Linetype><LinetypeScale><BasicPropInfo><PropValue unspecified="TRUE" valueType="3" value="0"/></BasicPropInfo></LinetypeScale><PlotStyle><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></PlotStyle><LineWeight><BasicPropInfo><PropValue unspecified="TRUE" valueType="2" value="0"/></BasicPropInfo></LineWeight><Transparency><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Transparency><Textstyle><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Textstyle><Dimstyle><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Dimstyle><Tablestyle><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Tablestyle></GeneralProperties><Command><Macro><![CDATA[^C^C_polygon ]]></Macro></Command></Data></Tool><Tool Revision="24.2.1" option="24"><ItemID idValue="{42359F47-D748-46BE-BF9D-AE5E770A4D10}"/><Properties><ItemName>Rectangle</ItemName><Images option="0"><Image cx="20" cy="20" IsDark="false" resource="RCDATA_16_RECTAN" src="%ProgramBtnRes%"/><Image cx="20" cy="20" IsDark="true" resource="RCDATA_16_RECTAN" src="%ProgramBtnRes%"/></Images><Description>Creates a rectangular polyline</Description><Time createdUniversalDateTime="2022-02-14T04:34:52" modifiedUniversalDateTime="2022-02-14T04:34:52"/></Properties><ToolType>1</ToolType><StockToolRef idValue="{2AE7120B-CEE4-47A5-9B50-EF9F3ADE24AC}"/><Data><GeneralProperties><Color><BasicPropInfo><PropValue unspecified="TRUE"/></BasicPropInfo></Color><Layer><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Layer><Linetype><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Linetype><LinetypeScale><BasicPropInfo><PropValue unspecified="TRUE" valueType="3" value="0"/></BasicPropInfo></LinetypeScale><PlotStyle><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></PlotStyle><LineWeight><BasicPropInfo><PropValue unspecified="TRUE" valueType="2" value="0"/></BasicPropInfo></LineWeight><Transparency><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Transparency><Textstyle><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Textstyle><Dimstyle><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Dimstyle><Tablestyle><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Tablestyle></GeneralProperties><Command><Macro><![CDATA[^C^C_rectang ]]></Macro></Command></Data></Tool><Tool Revision="24.2.1" option="24"><ItemID idValue="{A4C64B4F-222E-41A8-9B83-8AFEF449B1D1}"/><Properties><ItemName>Arc</ItemName><Images option="0"><Image cx="20" cy="20" IsDark="false" resource="RCDATA_16_ARC3PT" src="%ProgramBtnRes%"/><Image cx="20" cy="20" IsDark="true" resource="RCDATA_16_ARC3PT" src="%ProgramBtnRes%"/></Images><Description>Creates an arc using three points</Description><Time createdUniversalDateTime="2022-02-14T04:34:52" modifiedUniversalDateTime="2022-02-14T04:34:52"/></Properties><ToolType>1</ToolType><StockToolRef idValue="{2AE7120B-CEE4-47A5-9B50-EF9F3ADE24AC}"/><Data><GeneralProperties><Color><BasicPropInfo><PropValue unspecified="TRUE"/></BasicPropInfo></Color><Layer><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Layer><Linetype><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Linetype><LinetypeScale><BasicPropInfo><PropValue unspecified="TRUE" valueType="3" value="0"/></BasicPropInfo></LinetypeScale><PlotStyle><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></PlotStyle><LineWeight><BasicPropInfo><PropValue unspecified="TRUE" valueType="2" value="0"/></BasicPropInfo></LineWeight><Transparency><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Transparency><Textstyle><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Textstyle><Dimstyle><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Dimstyle><Tablestyle><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Tablestyle></GeneralProperties><Command><Macro><![CDATA[^C^C_arc ]]></Macro></Command></Data></Tool><Tool Revision="24.2.1" option="24"><ItemID idValue="{0C5B4931-4A44-484D-9EF5-1C85DC6B5382}"/><Properties><ItemName>Circle</ItemName><Images option="0"><Image cx="20" cy="20" IsDark="false" resource="RCDATA_16_CIRRAD" src="%ProgramBtnRes%"/><Image cx="20" cy="20" IsDark="true" resource="RCDATA_16_CIRRAD" src="%ProgramBtnRes%"/></Images><Description>Creates a circle using a center point and a radius</Description><Time createdUniversalDateTime="2022-02-14T04:34:52" modifiedUniversalDateTime="2022-02-14T04:34:52"/></Properties><ToolType>1</ToolType><StockToolRef idValue="{2AE7120B-CEE4-47A5-9B50-EF9F3ADE24AC}"/><Data><GeneralProperties><Color><BasicPropInfo><PropValue unspecified="TRUE"/></BasicPropInfo></Color><Layer><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Layer><Linetype><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Linetype><LinetypeScale><BasicPropInfo><PropValue unspecified="TRUE" valueType="3" value="0"/></BasicPropInfo></LinetypeScale><PlotStyle><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></PlotStyle><LineWeight><BasicPropInfo><PropValue unspecified="TRUE" valueType="2" value="0"/></BasicPropInfo></LineWeight><Transparency><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Transparency><Textstyle><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Textstyle><Dimstyle><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Dimstyle><Tablestyle><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Tablestyle></GeneralProperties><Command><Macro><![CDATA[^C^C_circle ]]></Macro></Command></Data></Tool><Tool Revision="24.2.1" option="0"><ItemID idValue="{B658EAB9-F59C-4D54-BFE2-B1EB15A3CD7E}"/><Properties><ItemName>Spline</ItemName><Images option="0"><Image cx="20" cy="20" IsDark="false" resource="RCDATA_16_SPLINE" src="%ProgramBtnRes%"/><Image cx="20" cy="20" IsDark="true" resource="RCDATA_16_SPLINE" src="%ProgramBtnRes%"/></Images><Description>Creates a smooth curve that passes through or near specified points</Description><Time createdUniversalDateTime="2022-02-14T04:44:14" modifiedUniversalDateTime="2022-02-14T04:44:14"/></Properties><CustomData>
											<AcRxClassInfo className="AcDbSpline"/>
											<ToolbarButton idButton="ID_Spline"/>
										</CustomData>
										<ToolType>2</ToolType><Flyout enable="true"><ShapePackage idValue="{4AFD3A7B-127C-468D-9DAD-D6D948BA8615}"/><CurrentShape idValue="{9E94EFA7-423D-4CED-AC1C-889A7BE3906B}"/></Flyout><StockToolRef idValue="{2AE7120B-CEE4-47A5-9B50-EF9F3ADE24AC}"/><Data>
											<GeneralProperties><Color><BasicPropInfo><PropValue unspecified="TRUE"/></BasicPropInfo></Color><Layer><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Layer><Linetype><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Linetype><LinetypeScale><BasicPropInfo><PropValue unspecified="TRUE" valueType="3" value="0"/></BasicPropInfo></LinetypeScale><PlotStyle><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></PlotStyle><LineWeight><BasicPropInfo><PropValue unspecified="TRUE" valueType="2" value="0"/></BasicPropInfo></LineWeight><Transparency><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Transparency><Textstyle><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Textstyle><Dimstyle><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Dimstyle><Tablestyle><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Tablestyle></GeneralProperties><Command><Macro><![CDATA[^C^C^R_spline ]]></Macro></Command></Data>
									</Tool><Tool Revision="24.2.1" option="24"><ItemID idValue="{E700CE5D-CFB9-4358-9A5A-87C05E229119}"/><Properties><ItemName>Ellipse</ItemName><Images option="0"><Image cx="20" cy="20" IsDark="false" resource="RCDATA_16_ELLAE" src="%ProgramBtnRes%"/><Image cx="20" cy="20" IsDark="true" resource="RCDATA_16_ELLAE" src="%ProgramBtnRes%"/></Images><Description>Creates an ellipse or an elliptical arc</Description><Time createdUniversalDateTime="2022-02-14T04:34:52" modifiedUniversalDateTime="2022-02-14T04:34:52"/></Properties><ToolType>1</ToolType><StockToolRef idValue="{2AE7120B-CEE4-47A5-9B50-EF9F3ADE24AC}"/><Data><GeneralProperties><Color><BasicPropInfo><PropValue unspecified="TRUE"/></BasicPropInfo></Color><Layer><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Layer><Linetype><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Linetype><LinetypeScale><BasicPropInfo><PropValue unspecified="TRUE" valueType="3" value="0"/></BasicPropInfo></LinetypeScale><PlotStyle><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></PlotStyle><LineWeight><BasicPropInfo><PropValue unspecified="TRUE" valueType="2" value="0"/></BasicPropInfo></LineWeight><Transparency><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Transparency><Textstyle><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Textstyle><Dimstyle><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Dimstyle><Tablestyle><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Tablestyle></GeneralProperties><Command><Macro><![CDATA[^C^C_ellipse ]]></Macro></Command></Data></Tool><Tool Revision="24.2.1" option="24"><ItemID idValue="{20C35F68-A9D2-44EF-83D4-5E0AF773B8A7}"/><Properties><ItemName>Hatch...</ItemName><Images option="0"><Image cx="20" cy="20" IsDark="false" resource="RCDATA_16_BHATCH" src="%ProgramBtnRes%"/></Images><Description>Fills an enclosed area or selected objects with a hatch pattern or fill</Description><Time createdUniversalDateTime="2022-05-06T03:09:13" modifiedUniversalDateTime="2022-05-06T03:09:13"/></Properties><ToolType>1</ToolType><StockToolRef idValue="{2AE7120B-CEE4-47A5-9B50-EF9F3ADE24AC}"/><Data><GeneralProperties><Color><BasicPropInfo><PropValue unspecified="TRUE"/></BasicPropInfo></Color><Layer><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Layer><Linetype><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Linetype><LinetypeScale><BasicPropInfo><PropValue unspecified="TRUE" valueType="3" value="0"/></BasicPropInfo></LinetypeScale><PlotStyle><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></PlotStyle><LineWeight><BasicPropInfo><PropValue unspecified="TRUE" valueType="2" value="0"/></BasicPropInfo></LineWeight><Transparency><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Transparency><Textstyle><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Textstyle><Dimstyle><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Dimstyle><Tablestyle><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Tablestyle></GeneralProperties><Command><Macro><![CDATA[^C^C_hatch ]]></Macro></Command></Data></Tool><Tool Revision="24.2.1" option="0"><ItemID idValue="{82374E94-DADB-4C6C-8B0A-48BB7E9412D5}"/><Properties><ItemName>Multiline Text...</ItemName><Images option="0"><Image cx="20" cy="20" IsDark="false" resource="RCDATA_16_MTEXT" src="%ProgramBtnRes%"/></Images><Description>Creates a multiline text object</Description><Time createdUniversalDateTime="2022-05-06T03:15:35" modifiedUniversalDateTime="2022-05-06T03:15:35"/></Properties><CustomData>
											<AcRxClassInfo className="AcDbMText"/>
											<ToolbarButton idButton="ID_Mtext"/>
										</CustomData>
										<ToolType>1</ToolType><StockToolRef idValue="{2AE7120B-CEE4-47A5-9B50-EF9F3ADE24AC}"/><Data>
											<GeneralProperties><Color><BasicPropInfo><PropValue unspecified="TRUE"/></BasicPropInfo></Color><Layer><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Layer><Linetype><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Linetype><LinetypeScale><BasicPropInfo><PropValue unspecified="TRUE" valueType="3" value="0"/></BasicPropInfo></LinetypeScale><PlotStyle><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></PlotStyle><LineWeight><BasicPropInfo><PropValue unspecified="TRUE" valueType="2" value="0"/></BasicPropInfo></LineWeight><Transparency><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Transparency><Textstyle><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Textstyle><Dimstyle><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Dimstyle><Tablestyle><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Tablestyle></GeneralProperties><Command><Macro><![CDATA[^C^C_mtext ]]></Macro></Command></Data>
									</Tool><Tool Revision="24.2.1" option="24"><ItemID idValue="{36827220-4424-41BB-BFE0-F0676EEB86C9}"/><Properties><ItemName>Edit...</ItemName><Images option="0"><Image cx="20" cy="20" IsDark="false" resource="RCDATA_16_TEXEDI" src="%ProgramBtnRes%"/></Images><Description>Edits text, dimension text, and attribute definitions</Description><Time createdUniversalDateTime="2022-05-06T03:09:13" modifiedUniversalDateTime="2022-05-06T03:09:13"/></Properties><ToolType>1</ToolType><StockToolRef idValue="{2AE7120B-CEE4-47A5-9B50-EF9F3ADE24AC}"/><Data><GeneralProperties><Color><BasicPropInfo><PropValue unspecified="TRUE"/></BasicPropInfo></Color><Layer><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Layer><Linetype><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Linetype><LinetypeScale><BasicPropInfo><PropValue unspecified="TRUE" valueType="3" value="0"/></BasicPropInfo></LinetypeScale><PlotStyle><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></PlotStyle><LineWeight><BasicPropInfo><PropValue unspecified="TRUE" valueType="2" value="0"/></BasicPropInfo></LineWeight><Transparency><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Transparency><Textstyle><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Textstyle><Dimstyle><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Dimstyle><Tablestyle><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Tablestyle></GeneralProperties><Command><Macro><![CDATA[^C^C_textedit ]]></Macro></Command></Data></Tool></Tools></Palette></PaletteContent><PaletteUI><CAdUiPalette PaletteStyle="1"/><CAcTcUiToolPalette><CatalogView ID="{4C6CD2DF-662E-4F45-AC8D-FE0E8B869967}"><ToolSource><Palette ID="{4C6CD2DF-662E-4F45-AC8D-FE0E8B869967}">mp-Draw</Palette></ToolSource><Image SizeCX="32" SizeCY="32"/><Style>493570</Style><ToolOrder><Tool ID="{DCA8FC24-AE40-4B85-AC1A-61D852762CE2}"/><Tool ID="{A3564D00-90E3-4147-8156-558F6C129BD4}"/><Tool ID="{2161258F-3E15-436E-9FBC-E8F25F509F36}"/><Tool ID="{EFDF30CF-4BC5-4BD9-9B4D-ADB08DA0AB4B}"/><Tool ID="{42359F47-D748-46BE-BF9D-AE5E770A4D10}"/><Tool ID="{A4C64B4F-222E-41A8-9B83-8AFEF449B1D1}"/><Tool ID="{0C5B4931-4A44-484D-9EF5-1C85DC6B5382}"/><Tool ID="{B658EAB9-F59C-4D54-BFE2-B1EB15A3CD7E}"/><Tool ID="{E700CE5D-CFB9-4358-9A5A-87C05E229119}"/><Tool ID="{20C35F68-A9D2-44EF-83D4-5E0AF773B8A7}"/><Tool ID="{82374E94-DADB-4C6C-8B0A-48BB7E9412D5}"/><Tool ID="{36827220-4424-41BB-BFE0-F0676EEB86C9}"/></ToolOrder></CatalogView></CAcTcUiToolPalette></PaletteUI></PaletteData></Palettes></PaletteSetContent><PaletteSetUI><CAdUiDockControlBar Orientation="59420" AllowDocking="1"><FloatInfo Left="6" Top="143" Width="172" Height="599"/><DockInfo Left="-1" Top="75" Width="269" Height="715" MRUDockID="59420"/></CAdUiDockControlBar><CAdUiPaletteSet ActivePaletteIndex="0" TitleBarLocation="0" AutoRollup="0" Name="Tool Palettes - my-palette" Style="4222" Opacity="100" RolloverOpacity="100" Visible="1"/></PaletteSetUI></PaletteSetData></PaletteSets></ToolPaletteExport>
